// <auto-generated />
namespace ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_Type_To_DateTime_In_TimeToPass_And_DateOfPass_In_PassedTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_Type_To_DateTime_In_TimeToPass_And_DateOfPass_In_PassedTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201606192146312_Change_Type_To_DateTime_In_TimeToPass_And_DateOfPass_In_PassedTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
